export const ERROR_CODES = {
  VALIDATION_ERROR: 'INVALID_PAYLOAD',
  UNAUTHENTICATED: 'AUTH_REQUIRED',
  FORBIDDEN: 'PERMISSION_DENIED',
  NOT_FOUND: 'HACKATHON_NOT_FOUND',
  REVIEW_EXISTS: 'REVIEW_EXISTS',
  BOOKMARK_EXISTS: 'BOOKMARK_EXISTS',
  RATE_LIMITED: 'RATE_LIMIT_EXCEEDED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
